(2025-04-28 13:43:15,410) ERROR    [exceptions]:: uID=RHivBE3cl9e2KpxOEcmb9Lu9BPM2 :: !! 500 !! POST /events uid=RHivBE3cl9e2KpxOEcmb9Lu9BPM2
Traceback (most recent call last):
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/portiaVenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/portiaVenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/logger.py", line 76, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/auth.py", line 60, in wrapper
    return f(uid, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/routes/events.py", line 24, in upsertEventComposite
    ids = upsertComposite(request.get_json() or {}, uID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/routes/composite.py", line 41, in upsertComposite
    eventID  = eventRef.id
               ^^^^^^^^
UnboundLocalError: cannot access local variable 'eventRef' where it is not associated with a value
(2025-04-28 13:47:23,038) ERROR    [exceptions]:: uID=RHivBE3cl9e2KpxOEcmb9Lu9BPM2 :: !! 500 !! POST /events uid=RHivBE3cl9e2KpxOEcmb9Lu9BPM2
Traceback (most recent call last):
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/portiaVenv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/portiaVenv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/logger.py", line 76, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/auth.py", line 60, in wrapper
    return f(uid, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/routes/events.py", line 24, in upsertEventComposite
    ids = upsertComposite(request.get_json() or {}, uID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/garri/Documents/SS2025/CIS658-WA/portiaApp/backend/routes/composite.py", line 41, in upsertComposite
    eventID  = eventRef.id
               ^^^^^^^^
UnboundLocalError: cannot access local variable 'eventRef' where it is not associated with a value
